/*
 * Problem: 78. Subsets
 *
 * ------------------------------------------------------------
 * STATEMENT:
 * Given an integer array nums, return all possible subsets
 * (the power set).
 *
 * The solution set must not contain duplicate subsets.
 * You may return the solution in any order.
 *
 * ------------------------------------------------------------
 * APPROACH: Backtracking (DFS)
 *
 * ------------------------------------------------------------
 * KEY OBSERVATION:
 *
 * 1️⃣ For every element, we have TWO choices:
 *    - Include the element
 *    - Exclude the element
 *
 * 2️⃣ All subsets can be generated by exploring these choices
 *    recursively while maintaining order.
 *
 * ------------------------------------------------------------
 * STRATEGY:
 *
 * - Use backtracking to build subsets incrementally
 * - At every recursive call:
 *   → Current subset is a valid subset → add it to answer
 * - Move forward to avoid duplicates
 *
 * ------------------------------------------------------------
 * RECURSIVE FUNCTION PARAMETERS:
 *
 * backtrack(start, nums, curr, ans)
 *
 * start → index from where we can pick elements
 * nums  → input array
 * curr  → current subset being formed
 * ans   → stores all subsets
 *
 * ------------------------------------------------------------
 * ALGORITHM STEPS:
 *
 * 1️⃣ Start with an empty subset
 * 2️⃣ Add current subset to answer
 * 3️⃣ Loop from index = start to n-1:
 *    - Pick nums[i]
 *    - Recurse for next index (i + 1)
 *    - Backtrack by removing last element
 *
 * ------------------------------------------------------------
 * DRY RUN EXAMPLE:
 *
 * nums = [1, 2]
 *
 * Subsets generated:
 * []
 * [1]
 * [1, 2]
 * [2]
 *
 * ------------------------------------------------------------
 * TIME & SPACE COMPLEXITY:
 *
 * Time Complexity:
 * - O(2^n)
 *   (Each element has include/exclude choice)
 *
 * Space Complexity:
 * - O(n) recursion stack
 * - O(2^n) to store all subsets
 *
 * ------------------------------------------------------------
 * INTERVIEW NOTES:
 *
 * - Classic backtracking problem
 * - Always add current subset before branching
 * - Order of recursion ensures no duplicates
 */

class Solution {
private:
    void backtrack(int start,
                   vector<int> nums,
                   vector<int> &curr,
                   vector<vector<int>> &ans) {

        // Current subset is valid → add to answer
        ans.push_back(curr);

        // Explore further elements
        for (int i = start; i < nums.size(); i++) {

            // Choose the current element
            curr.push_back(nums[i]);

            // Recurse with next index
            backtrack(i + 1, nums, curr, ans);

            // Backtrack: remove last chosen element
            curr.pop_back();
        }
    }

public:
    vector<vector<int>> subsets(vector<int>& nums) {
        vector<vector<int>> ans;   // stores all subsets
        vector<int> curr;          // current subset

        // Start backtracking from index 0
        backtrack(0, nums, curr, ans);

        return ans;
    }
};
