/*
 * Problem: 389. Find the Difference
 *
 * Statement:
 * You are given two strings `s` and `t`.
 * String `t` is generated by shuffling string `s` and
 * ADDING ONE extra character at a random position.
 *
 * Your task is to find and return the EXTRA character.
 *
 * ------------------------------------------------------------
 * APPROACH 1: Frequency Map (Your Approach)
 *
 * Core Idea:
 * - Count frequency of characters in `t`
 * - Subtract frequency using characters of `s`
 * - The character with remaining positive frequency
 *   is the extra character
 *
 * ------------------------------------------------------------
 * Step-by-Step Algorithm (Approach 1):
 *
 * 1. Create an unordered_map `freq`
 *    - Key   → character
 *    - Value → frequency
 *
 * 2. Traverse string `t`:
 *      freq[c]++
 *
 * 3. Traverse string `s`:
 *      freq[ch]--
 *
 * 4. Traverse the map:
 *    - The character whose frequency > 0
 *      is the extra character
 *
 * ------------------------------------------------------------
 * Example:
 *
 * s = "abcd"
 * t = "abcde"
 *
 * After counting:
 * e → 1   (all others become 0)
 *
 * Output = 'e'
 *
 * ------------------------------------------------------------
 * Time Complexity:
 * - O(n)
 *
 * Space Complexity:
 * - O(n)
 *   Hash map storage
 *
 * ------------------------------------------------------------
 * APPROACH 2: XOR Trick (BEST & OPTIMAL)
 *
 * Core Insight:
 *
 * - XOR of a number with itself is 0
 * - XOR of a number with 0 is the number itself
 *
 * Since:
 * - All characters of `s` appear in `t`
 * - Except ONE extra character
 *
 * XOR-ing all characters of `s` and `t` together
 * will CANCEL out matching characters
 * leaving only the extra character
 *
 * ------------------------------------------------------------
 * Step-by-Step Algorithm (Approach 2):
 *
 * 1. Initialize char `res = 0`
 *
 * 2. Traverse string `s`:
 *      res ^= ch
 *
 * 3. Traverse string `t`:
 *      res ^= ch
 *
 * 4. Return `res`
 *
 * ------------------------------------------------------------
 * Why Approach 2 Is Better:
 *
 * - O(n) time
 * - O(1) space
 * - Extremely clean and elegant
 * - Interview favorite
 *
 * ------------------------------------------------------------
 * Time & Space Comparison:
 *
 * | Approach | Time | Space | Recommended |
 * |--------|------|-------|-------------|
 * | Map    | O(n) | O(n) | ❌ |
 * | XOR    | O(n) | O(1) | ✅ |
 *
 * ------------------------------------------------------------
 * Edge Cases:
 *
 * - Single character strings
 * - Repeated characters
 *
 * ------------------------------------------------------------
 * Pattern Recognition:
 *
 * This is a classic:
 *   "XOR cancellation" problem
 *
 * Seen in:
 * - Single number problems
 * - Missing number
 * - Find extra element
 */

#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    // -----------------------------
    // Approach 1: Frequency Map
    // -----------------------------
    char findTheDifference(string s, string t) {
        unordered_map<char,int> freq;

        for (char c : t)
            freq[c]++;

        for (char ch : s)
            freq[ch]--;

        char res = 0;
        for (auto fr : freq) {
            if (fr.second > 0)
                res = fr.first;
        }
        return res;
    }

    /*
    // -----------------------------
    // Approach 2: XOR Trick (Optimal)
    // -----------------------------
    char findTheDifference(string s, string t) {
        char res = 0;

        for (char ch : s)
            res ^= ch;

        for (char ch : t)
            res ^= ch;

        return res;
    }
    */
};
